# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", :path => "../../jekyll" if Dir.exist?("../../jekyll")

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-locale", :path => ".."
end
