require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/CyclomaticComplexity:
  Max: 7
Style/ClassAndModuleChildren:
  Enabled: false
Style/MultipleComparison:
  Enabled: false
Style/RedundantSelf:
  Exclude:
    - lib/jekyll/locale/mixins/helper.rb
