require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 7
Style/ClassAndModuleChildren:
  Enabled: false
