sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.4
  - 2.3

env:
  - TEST_SUITE=rspec
  - TEST_SUITE=cucumber

branches:
  only:
    - master

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: bash ./script/cibuild

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
